name: Compile dpkg

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Declare short commit variable
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Install everything
      run: |
        echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ focal main' > /etc/apt/sources.list.d/deb-src.list
        echo 'deb-src http://security.ubuntu.com/ubuntu focal-security main' >> /etc/apt/sources.list.d/deb-src.list
        
        sudo apt install build-essential dpkg-dev pixz
        sudo apt build-dep dpkg
        mkdir build && cd build
        apt source dpkg
        cd dpkg-*
        patch -p1 -i ../../dpkg-pixz-decompress.patch
        dpkg-buildpackage --no-sign
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
          path: |
            build/dpkg-*/dpkg_*.deb
