name: Tuned

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
    - name: Disable fontconfig trigger
      run: sudo sed '/fontconfig/d' -i /var/lib/dpkg/triggers/File
    - name: Disable install-info trigger
      run: sudo sed '/install-info/d' -i /var/lib/dpkg/triggers/File
    - name: Disable mime related triggers
      run: sudo sed '/mime/d' -i /var/lib/dpkg/triggers/File
    - name: Disable hicolor icon theme triggers
      run: sudo sed '/hicolor-icon-theme/d' -i /var/lib/dpkg/triggers/File
    - name: Enable unsafe dpkg IO
      run: echo "force-unsafe-io" | sudo tee -a /etc/dpkg/dpkg.cfg.d/force-unsafe-io
    - name: Update apt sources
      run: sudo apt-get update -y
    - name: Install libguestfs-tools
      run: sudo apt-get install libguestfs-tools valgrind vagrant kde-baseapps -y
