name: Tuned

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: echo 'man-db man-db/auto-update boolean false' |sudo debconf-set-selections
    - name: Update apt sources
      run: sudo apt-get update -y
    - name: Install libguestfs-tools
      run: sudo apt-get install libguestfs-tools -y
