name: Tuned

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
    - name: Disable fontconfig trigger
      run: sudo sed '/fontconfig/d' -i /var/lib/dpkg/triggers/File
    - name: Disable install-info trigger
      run: sudo sed '/install-info/d' -i /var/lib/dpkg/triggers/File
    - name: Update apt sources
      run: sudo apt-get update -y
    - name: Install libguestfs-tools
      run: sudo apt-get install libguestfs-tools -y
